apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: scd-project
  labels:
    app: mern-app
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5173
    nodePort: 30008  # Changed from 30007 to avoid potential conflicts
  selector:
    app: mern-app
    tier: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: scd-project
  labels:
    app: mern-app
    tier: backend
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: mern-app
    tier: backend
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: scd-project
  labels:
    app: mern-app
    tier: database
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mern-app
    tier: database