name: Build and Deploy to Minikube
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        eval $(minikube docker-env)

    - name: Build Docker image for backend
      run: |
        cd backend
        docker build -t subhan0072/my-node-backend:latest .

    - name: Build Docker image for frontend
      run: |
        cd frontend
        docker build -t subhan0072/my-node-frontend:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image for backend
      run: docker push subhan0072/my-node-backend:latest

    - name: Push Docker image for frontend
      run: docker push subhan0072/my-node-frontend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml